name: sd_moveis_ar
description: "A new Flutter project for SD Móveis AR Studio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # The native cross-platform AR plugin (ARCore/ARKit)
  ar_flutter_plugin: ^0.7.3
  
  # Standard math dependency for 3D matrices & distance calculation
  vector_math: 2.2.0

  # Icons for Material UI
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.10.0
  
  # Database & Screenshot integration
  supabase_flutter: ^2.0.4
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

  # Core Infrastructure (Downgraded for AR Plugin compatibility)
  permission_handler: ^11.3.0
  geolocator: ^9.0.2

dependency_overrides:
  permission_handler: ^11.3.0
  permission_handler_android: 12.0.12
  permission_handler_apple: 9.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # As assets em .glb que o projeto irá referenciar internamente (Exemplo)
  # assets:
  #   - assets/models/sofa.glb
  #   - assets/models/table.glb
