-- Expand itens_projeto table to support all OSItem fields
ALTER TABLE public.itens_projeto
  ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT 'un',
  ADD COLUMN IF NOT EXISTS width NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_m2 NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_table TEXT NOT NULL DEFAULT 'avista',
  ADD COLUMN IF NOT EXISTS price_avista NUMERIC,
  ADD COLUMN IF NOT EXISTS price_aprazo NUMERIC,
  ADD COLUMN IF NOT EXISTS price_atacado NUMERIC;
