// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nglwscakhhdhelhbqkyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_3fJ0EGv8wuNn1J95sj1G1A_21WFWOR2";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});